### ISSUE TITLE
invalid syntax in DNASuitPoint.py

### ISSUE THREAD

**Issue by AntiPositive** [loblao/libpandadna#57]
http://prntscr.com/e2xwsy

This is not a dna issue, I've tried this with 3 different dna files and each had an identical issue.

**Comment by mfwass** [comment]
What version of Python are you using?  This is syntactically correct in Python 2.7

**Comment by UnknownProjecter** [comment]
I think its 1.1.8??? I'm doing it for the TTI source.

**Comment by s0r00t** [comment]
That's not a Python version.

**Comment by UnknownProjecter** [comment]
can you send me the right python? i just need to know where and maybe i can
link you my discord?

**Comment by mfwass** [comment]
Practical programming knowledge is required in order to work on a massive programming project.  I suggest learning more about the language you're using before you take on something like a MMO.

Also, there are **plenty** of public alternatives than using stolen source code.  Such as the already open game [Toontown Rewritten](https://toontownrewritten.com) *(which you just happen to be using stolen code from)*.  :)

**Comment by mfwass** [comment]
Please ensure you're using Python 2.7.  I'm certain you're using an incompatible version of Python.
